### PR TITLE
update to OPTEE 3.13.0

### PR DESCRIPTION
**Pull request by fanrong1992**
Hi @mssun,
I have upgraded the sdk to OPTEE 3.13.0. The changes are:
1. Upgrade optee submodules to 3.13.0 (optee_client, optee_os, build in optee/)
2. Modify Makefile in sdk
All the examples has been tested on OPTEE 3.13.0's Qemu emulator.

Best regards,
Rong Fan

### CODE REVIEW

**Comment by mssun** [comment]
Thanks. I believe the `tests/screenlog.0` file is not needed.

**Comment by mssun** [comment]
Can you also update the getting started doc (`docs/getting-started-with-optee-for-qemu-armv8.md`)?

**Comment by fanrong1992** [comment]
OK, these two files has been updated.

**Comment by mssun** [comment]
Do you know why the CI failed?

**Comment by fanrong1992** [comment]
Sorry, it's my fault. I didn't pack qemu-system-aarch64 into optee-qemuv8-3.13.0.tar.gz. I repackaged the optee-qemuv8-3.13.0.tar.gz and trouble you to upload again.

**Pull request merged**
